const GAMES = [
  {
    id:"GTA5Mobile",
    title:"GTA 5 Mobile",
    image:"https://www5.0zz0.com/2023/10/15/08/332140079.jpeg",
    version:"v1.0.3095/1.68",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.8 (241,332 reviews)",
    description:"Experience the legendary open-world action of GTA 5 optimized for mobile. Enjoy missions, free roaming, vehicles, and enhanced graphics.",
    android:"https://www.mediafire.com/file_premium/tuul6uefy9gyp9n/gta_v_.apk/file",
    ios:"https://www.mediafire.com/file_premium/tuul6uefy9gyp9n/gta_v_.apk/file"
  },
  {
    id:"GTAViceCity",
    title:"GTA Vice City",
    image:"https://i.postimg.cc/gjzQQ2sb/1680953248-gtavc.png",
    version:"v3.9.6",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.6 (189,210 reviews)",
    description:"Return to Vice City with classic missions, iconic characters, and full controller support on mobile.",
    android:"https://play.google.com/store/apps/details?id=com.rockstargames.gtavc",
    ios:"https://apps.apple.com/app/id578448682"
  },
  {
    id:"GTASanAndreas",
    title:"GTA San Andreas",
    image:"https://i.postimg.cc/nLw1pcnt/unnamed.webp",
    version:"v2.0.0",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.7 (320,554 reviews)",
    description:"Explore the massive world of San Andreas with RPG elements, gang wars, and an epic storyline.",
    android:"https://play.google.com/store/apps/details?id=com.rockstargames.gtasa",
    ios:"https://apps.apple.com/app/id763692274"
  },
  {
    id:"RedDeadRedemption2Mobile",
    title:"Red Dead Redemption 2 Mobile",
    image:"https://i.postimg.cc/jqkbzjTB/rdr2.jpg",
    version:"v1.5.2",
    stars:"★★★★★",
    rating:"★★★★★ 4.9 (410,982 reviews)",
    description:"A cinematic open-world western adventure with immersive storytelling and realistic gameplay.",
    android:"#",
    ios:"#"
  },
  {
    id:"AssettoCorsaMobile",
    title:"Assetto Corsa Mobile",
    image:"https://i.postimg.cc/3xHVQWW0/Picsart-25-02-25-00-54-38-367-1.jpg",
    version:"v1.16.4",
    stars:"★★★★★",
    rating:"★★★★★ 4.9 (198,113 reviews)",
    description:"Ultra-realistic racing simulation with licensed cars, tracks, and professional physics engine.",
    android:"#",
    ios:"#"
  },
  {
    id:"BeamNGdriveMobile",
    title:"BeamNG.drive Mobile",
    image:"https://i.postimg.cc/k5skc9J6/Picsart-25-03-08-05-57-01-681.jpg",
    version:"v0.32.0.0",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.6 (154,877 reviews)",
    description:"Advanced vehicle physics and soft-body damage simulation in an open sandbox environment.",
    android:"#",
    ios:"#"
  },
  {
    id:"EuroTruckSimulator2",
    title:"Euro Truck Simulator 2",
    image:"https://i.postimg.cc/kXfCsxTX/32aee5919f1c4e81da58627d21b3323a.jpg",
    version:"v1.0.0",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.5 (210,441 reviews)",
    description:"Drive powerful trucks across Europe, manage your company, and enjoy realistic driving mechanics.",
    android:"#",
    ios:"#"
  },
  {
    id:"ForzaHorizon5",
    title:"Forza Horizon 5",
    image:"https://sm.ign.com/ign_nordic/cover/f/forza-hori/forza-horizon-5_5jjv.jpg",
    version:"v1.656.386.0",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.8 (387,994 reviews)",
    description:"An open-world racing festival set in Mexico with stunning visuals and hundreds of cars.",
    android:"#",
    ios:"#"
  },
  {
    id:"TheCrewMotorfestMobile",
    title:"The Crew Motorfest Mobile",
    image:"https://i.postimg.cc/RVnTsbH8/the-crew-motorfest-download-The-Crew-Motor-Fest-1.avif",
    version:"v2.4.1",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.6 (129,881 reviews)",
    description:"High-speed arcade racing with exotic cars, multiplayer events, and open-world exploration.",
    android:"#",
    ios:"#"
  },
  {
    id:"HollowKnightSilksong",
    title:"Hollow Knight: Silksong",
    image:"https://i.postimg.cc/Mpm2MDqF/Fr-Mkduml-Mozlmzk-APFqq-D1y-Gwo-OJ.webp",
    version:"v1.8.2",
    stars:"★★★★★",
    rating:"★★★★★ 4.9 (275,610 reviews)",
    description:"A beautiful hand-crafted action platformer with challenging combat and deep lore.",
    android:"#",
    ios:"#"
  },
  {
    id:"CarXDriftRacing2",
    title:"CarX Drift Racing 2",
    image:"https://i.postimg.cc/XJxx1y6b/CARX-DRIFT-RACING-2-LOGO-VS-MODS.png",
    version:"v4.21.0",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.5 (312,448 reviews)",
    description:"Professional drift racing with tuning, multiplayer battles, and realistic controls.",
    android:"https://play.google.com/store/apps/details?id=com.carxtech.carxdr2",
    ios:"https://apps.apple.com/app/id1198510468"
  },
  {
    id:"FC24Mobile",
    title:"FC 24 Mobile",
    image:"https://image.api.playstation.com/vulcan/ap/rnd/202310/0214/c21c0669eaca7f3e02c41cad5e1a20f867aafcf14104f046.png",
    version:"v17.2.01",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.4 (981,774 reviews)",
    description:"The latest football experience with real teams, players, and online competitions.",
    android:"https://play.google.com/store/apps/details?id=com.ea.gp.fifamobile",
    ios:"https://apps.apple.com/app/id1094930513"
  },
  {
    id:"Efootball2024",
    title:"eFootball 2024",
    image:"https://www.konami.com/img/common/sp_js_img/main_sp_kde_efootball2024_0908.jpg",
    version:"v3.8.0",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.3 (712,998 reviews)",
    description:"Next-generation football gameplay with realistic physics and online PvP modes.",
    android:"https://play.google.com/store/apps/details?id=jp.konami.pesam",
    ios:"https://apps.apple.com/app/id1117270703"
  },
  {
    id:"DreamLeagueSoccer",
    title:"Dream League Soccer",
    image:"https://m.media-amazon.com/images/I/41GZrXhv0BL.jpg",
    version:"v11.07",
    stars:"★★★★★",
    rating:"★★★★★ 4.9 (1,204,663 reviews)",
    description:"Build your dream team, compete online, and enjoy smooth football gameplay.",
    android:"https://play.google.com/store/apps/details?id=com.firsttouchgames.dls7",
    ios:"https://apps.apple.com/app/id1462911602"
  },
  {
    id:"NBA2K23Mobile",
    title:"NBA 2K23 Mobile",
    image:"https://assets.2k.com/1a6ngf98576c/4oCqsi6G8MfDjHKhjhBtrP/d43164117e00d78c0cf85dfafeb3b906/NBA23-WEBSITE-ATHLETE_HUB-MODULE1-STD_THUMBNAIL-828x828.jpg",
    version:"v124.0.1",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.6 (458,912 reviews)",
    description:"Authentic NBA basketball with real players, seasons, and competitive online modes.",
    android:"#",
    ios:"#"
  },
  {
    id:"Minecraft",
    title:"Minecraft",
    image:"https://i.imgur.com/VkL6g46.png",
    version:"v1.20.1",
    stars:"★★★★★",
    rating:"★★★★★ 5.0 (5,812,442 reviews)",
    description:"Create, explore, and survive in an infinite block-based world with endless possibilities.",
    android:"https://play.google.com/store/apps/details?id=com.mojang.minecraftpe",
    ios:"https://apps.apple.com/app/id479516143"
  },
  {
    id:"SnowRunner",
    title:"SnowRunner",
    image:"https://i.postimg.cc/C52bdZfM/snow.jpg",
    version:"v1.6.4",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.7 (233,554 reviews)",
    description:"Extreme off-road simulation with realistic terrain, vehicles, and physics.",
    android:"#",
    ios:"#"
  },
  {
    id:"SpiderManUnlimited",
    title:"Spider-Man Unlimited",
    image:"https://upload.wikimedia.org/wikipedia/en/a/aa/Spider-Man_Unlimited.png",
    version:"v4.5.2",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.5 (622,341 reviews)",
    description:"Endless runner action starring Spider-Man with fast-paced combat and villains.",
    android:"#",
    ios:"#"
  },
  {
    id:"HitmanSniper",
    title:"Hitman Sniper",
    image:"https://lh3.googleusercontent.com/PYlSCwbwrv6JFzp0-KtITrrN2VK4iCdEYK_9yBiADhV_vR5V-cAzrQcdDJu_rUz8BgMxU0aQpgEaypMneKXp",
    version:"v1.9.3",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.7 (341,772 reviews)",
    description:"Tactical sniper missions with stealth mechanics and replayability.",
    android:"https://play.google.com/store/apps/details?id=com.squareenixmontreal.hitmansniperandroid",
    ios:"https://apps.apple.com/app/id904278510"
  },
  {
    id:"FiveNightsAtFreddys",
    title:"Five Nights at Freddy's",
    image:"https://lh3.googleusercontent.com/b8dLwIWegBN_xEi2JS63DMbs5u3T1QVOaT194EiNfvN0IZctc2SLwp916Uqw3ECN9q_l-KPx2Oozee2oPoYiWn7e",
    version:"v2.0.8",
    stars:"★★★★★",
    rating:"★★★★★ 4.8 (812,904 reviews)",
    description:"Terrifying survival horror experience with intense atmosphere and strategy.",
    android:"https://play.google.com/store/apps/details?id=com.scottgames.fnaf1",
    ios:"https://apps.apple.com/app/id912536422"
  },
  {
    id:"PoppyPlaytimeMobile",
    title:"Poppy Playtime",
    image:"https://cdn.now.gg/apps-content/com.MOBGames.PoppyMobileChap1/icon/poppy-playtime.png",
    version:"v2.1.6",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.6 (298,114 reviews)",
    description:"A creepy puzzle horror adventure inside an abandoned toy factory.",
    android:"https://play.google.com/store/apps/details?id=com.MOBGames.PoppyMobileChap1",
    ios:"https://apps.apple.com/app/id1617275876"
  },
  {
    id:"VeryLittleNightmares",
    title:"Very Little Nightmares",
    image:"https://apkvision.org/wp-content/uploads/2020/01/Very-Little-Nightmares-2-140x140.png",
    version:"v1.5.3",
    stars:"★★★★★",
    rating:"★★★★★ 4.9 (176,332 reviews)",
    description:"Dark atmospheric puzzle adventure set in the Little Nightmares universe.",
    android:"https://play.google.com/store/apps/details?id=eu.bandainamcoent.verylittlenightmares",
    ios:"https://apps.apple.com/app/id1435140814"
  },
  {
    id:"FarmingSimulator23",
    title:"Farming Simulator 23",
    image:"https://assets-prd.ignimgs.com/2023/05/01/farmingsim23-1682967114647.jpg",
    version:"v1.4.2",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.5 (198,877 reviews)",
    description:"Manage your own farm with licensed machinery and realistic farming mechanics.",
    android:"https://play.google.com/store/apps/details?id=com.giantssoftware.fs23.google",
    ios:"https://apps.apple.com/app/id1618613474"
  },
  {
    id:"AvatarWorld",
    title:"Avatar World",
    image:"https://i.postimg.cc/brjhdg3p/1755341108-1.webp",
    version:"v1.9.7",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.4 (142,553 reviews)",
    description:"Creative role-play game where you design characters and build stories.",
    android:"#",
    ios:"#"
  },
  {
    id:"PS3EmulatorMobile",
    title:"PS3 Emulator Mobile",
    image:"https://i.postimg.cc/Y9GBqZ7v/ps3emulator.jpg",
    version:"v3.2.8",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.3 (99,881 reviews)",
    description:"Experimental PS3 emulator allowing classic console experiences on mobile.",
    android:"#",
    ios:"#"
  },
  {
    id:"ProSoccerOnline",
    title:"Pro Soccer Online",
    image:"https://www.mandatory.gg/wp-content/uploads/mandatory-zlan-2022-pro-soccer-online-meta.png",
    version:"v2.5.1",
    stars:"★★★★☆",
    rating:"★★★★☆ 4.5 (188,992 reviews)",
    description:"Competitive online football game with skill-based gameplay and ranked matches.",
    android:"#",
    ios:"#"
  },
  {
    id:"DemonSlayerOnline",
    title:"Demon Slayer: Blade Battle",
    image:"https://example.com/images/demon-slayer-blade-battle.png",
    version:"v1.8.2",
    stars:"★★★★★",
    rating:"★★★★★ 4.8 (256,734 reviews)",
    description:"Epic action RPG based on Demon Slayer, featuring fast-paced combat and stunning anime graphics.",
    android:"#",
    ios:"#"
}
];
